### ISSUE TITLE
[Bug]:  DOMException: Failed to execute 'matches' on 'Element': 'child-active):focus-within .n-menu-item-content__icon' is not a valid selector.

### ISSUE THREAD

**Issue by JoeABCDEF** [canvg/canvg#1700]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

It cannot be resolved at this time
```css
.n-menu .n-menu-item-content:not(.n-menu-item-content--disabled):not(.n-menu-item-content--selected, child-active):focus-within .n-menu-item-content__icon {

 color: var(--n-item-icon-color-hover);
 
}
```

Hopefully this selector can be resolved

### Reproduction

无

### Canvg version

4.0.1
